### ISSUE TITLE
🏁 Race of Sloths: The Open Source Developer Challenge is about to start

### ISSUE THREAD

**Issue by akorchyn** [eslint/js#635]
As a team of Rust developers from [Race of Sloths](https://race-of-sloths.com/),  we recognized this repo to be highly valuable in the open-source movement.

Race of Sloth makes the open-source contributions more fun and rewarding.

* This issue is an invitation to check how Race of Sloths works
* To accept the invitation, comment @race-of-sloths accept
* Once the invitation is accepted, your contributors are eligible participate in the Race
* Contributors just need to mention @race-of-sloths in their PR within your normal contribution flow
* We invite you for collaboration and making open source development more engaging together!

**Comment by nzakas** [comment]
This looks like spam. If you think this repo should be included in this project, please explain why (nothing here is written in Rust).

**Comment by akorchyn** [comment]
Hey. First of all thanks for the reply.

We are a small team of Rust engineers, but we want to make the open-source activity more fun. We do that by trying to gamify the process. 

I think the message is misleading a bit but we are not exclusive to Rust.  You can take a look at the [project](https://race-of-sloths.com/projects) page to see that there are already some JS, Python, and of course Rust repositories.  The biggest one is probably the Ant CSS component library that joined lately.

EsLint is a widely adopted tool, even I use it from time to time, haha. Thanks for your hard work on that. As our initial attempt to get beyond the root point, we do want to start with tools that we use in our projects and the libraries that are our dependencies, so that's how we get here :)

**Comment by nzakas** [comment]
Okay. This doesn't seem like it fits into the way we're doing things, so we'll pass. Thanks.
